# Generated by Django 4.1.2 on 2023-11-20 00:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=30)),
                ('kilometraje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('message', ckeditor.fields.RichTextField(blank=True, verbose_name='Cartelera de Mensaje')),
                ('imagendoc', models.ImageField(null=True, upload_to='img/', verbose_name='Cargue su Documento')),
                ('tipocontacto', models.IntegerField(choices=[[0, 'Pedido de Informacion'], [1, 'Consultoria de Polizas'], [2, 'Presupuesto']], verbose_name='Tipo de Contacto')),
                ('subs', models.BooleanField(blank=True, default=False, verbose_name='Subscribete a Correos informativos mensuales')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('registro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('vida', 'Vida'), ('auto', 'Auto'), ('viaje', 'Viaje'), ('empresarial', 'Empresarial'), ('casa', 'Casa'), ('mascota', 'Mascota')], max_length=15, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefonoContacto', models.IntegerField(null=True)),
                ('emailContacto', models.EmailField(max_length=45, null=True)),
                ('imagendocumento', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
