# Generated by Django 4.1.2 on 2023-11-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0002_alter_poliza_descripcion_alter_poliza_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
