# Generated by Django 4.1.2 on 2023-11-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0004_alter_poliza_descripcion_alter_poliza_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='imagendocumento',
            field=models.ImageField(blank=True, null=True, upload_to='contactos/'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
