# Generated by Django 4.1.2 on 2023-11-20 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Baseapp', '0007_alter_perfil_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='UserExtension',
        ),
    ]
