# Generated by Django 4.1.2 on 2023-11-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0011_alter_userextension_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='user',
        ),
    ]
