# Generated by Django 4.1.2 on 2023-11-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0014_alter_userextension_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
