# Generated by Django 4.1.2 on 2023-11-21 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Baseapp', '0015_alter_userextension_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userextension',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
