# Generated by Django 4.1.2 on 2023-11-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0017_auto_anio_auto_fotoauto_auto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='anio',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='fotoauto',
            field=models.ImageField(blank=True, null=True, upload_to='autos/', verbose_name='Foto Del Vehiculo'),
        ),
    ]
