# Generated by Django 4.1.2 on 2023-11-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0019_muro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Muro',
        ),
    ]
