# Generated by Django 4.1.2 on 2023-11-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0021_remove_poliza_nombre_poliza_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poliza',
            old_name='users',
            new_name='nombre',
        ),
    ]
