# Generated by Django 4.1.2 on 2023-11-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0022_rename_users_poliza_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
