# Generated by Django 4.1.2 on 2023-11-23 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Baseapp', '0024_auto_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
