# Generated by Django 4.1.2 on 2023-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0025_alter_auto_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='propietario',
            field=models.CharField(max_length=50, verbose_name='Propietario'),
        ),
    ]
